openapi: 3.0.2
info:
  title: FDK Event Harvester
  description: Harvests events (CPSV-AP cv:Event) from public-service endpoints
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: events
    description: CPSV-AP cv:Event
servers:
  - url: 'https://events.fellesdatakatalog.digdir.no'
    description: Produksjonsmiljø
  - url: 'https://events.staging.fellesdatakatalog.digdir.no'
    description: Testmiljø
  - url: 'https://events.demo.fellesdatakatalog.digdir.no'
    description: Demomiljø
paths:
  /events:
    get:
      tags:
        - events
      description: Returns a collection of events
      operationId: getEvents
      parameters:
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
  '/events/{id}':
    get:
      tags:
        - events
      description: Returns an event
      operationId: getEventById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Dataset catalog with requested id does not exist
  '/update/meta':
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - events
      description: Updates stored turtle files with current meta data for events
      operationId: updateMetaData
      responses:
        '204':
          description: No Content

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
